= Senior project and Open Source Readme

== Git Tutor

=== Version 0.3.0

=== Senior Project Group:

Joseph Walker, Chaskarandeep Singh,Deep Patel

== Rules:

1. Please do not complete your own pull requests if there is a large amount of commits.  Those pull requests should be reviewed by a second group member.

2. Commit and Push often.

== Git command line Senior Project:

=== Contributors - 

Joseph Walker, Chaskarandeep Singh, Deep Patel, Ori Maci, Sarthak Khatiwada

=== Instructions:

*Set up*

1.  If Deep or Mentu, fork this repository and clone your own fork.

2.  Otherwise, Clone this repository. `git clone https://github.com/joey-walker/COMP650-SeniorProject.git`

3.  To start your development environment, enter the COMP650-SeniorProject directory. `cd Comp650-SeniorProject`

4.  `vagrant up`

5.  After vagrant initializes, do `vagrant ssh` to login.

6.  Optional - become (G)root `sudo -s`.  Otherwise you may need to have sudo before most commands.

7.  `vagrant suspend` when you are done working to suspend the VM.  `vagrant destroy` to destroy the VM itself.

*To install*

1. Enter the git directory we cloned in `cd git`

2. type `make install`

*To switch git versions in vagrant*

>Ask Prof. Joey (cause I'm lazy), probably some meddling with the PATH.

=== Git instructions for fetching, merging, and pushing work

All development to the command line will be done on the senior-dev branch.  I (Joey) will do development joey-dev branch,
so please do not delete the branch after pull requests.

These are the available remotes:

`
deep    https://github.com/deeppatel824/git.git (fetch)

deep    https://github.com/deeppatel824/git.git (push)

joey    https://github.com/joey-walker/git.git (fetch)

joey    https://github.com/joey-walker/git.git (push)

mentu   https://github.com/chaskaransingh/git.git (fetch)

mentu   https://github.com/chaskaransingh/git.git (push)

ori     https://github.com/OzzyOrc/git.git (fetch)

ori     https://github.com/OzzyOrc/git.git (push)

origin  https://github.com/joey-walker/git.git (fetch)

origin  https://github.com/joey-walker/git.git (push)

sarthak https://github.com/sarthakcfc/git.git (fetch)

sarthak https://github.com/sarthakcfc/git.git (push)

upstream        https://github.com/git/git.git (fetch)

upstream        https://github.com/git/git.git (push) 
`
also available by typing `git remote -v`

*Fetching and merging:*

At the start of doing any form of work, first grab commits from the official git repository:

1. `git fetch upstream`

2. `git merge upstream/master`

Then grab commits from our central git repository for this group's commits.

1. `git fetch origin`

2. `git merge origin/master`

Fix any merge conflicts from here on before continuing work.

*Adding, committing, pushing*

1. `git add . (or specific files/directories instead of .)`

2. `git commit -m "message here"`

Push by doing the following

1. `git push your-name-here`

If you cloned from git the repository.  I recommend switching the default view on Github to the senior-dev branch.

*Pull Requests*

1.  To submit work, do a pull request at https://github.com/joey-walker/git .  Go to pull requests and confirm merge, or wait till someone merges it in for you.

== Git Gui Senior Project:

=== Contributors - 

Joseph Walker, Chaskarandeep Singh, Deep Patel

=== Instructions:

Coming soon.