= Senior project and Open Source Readme

== Git Tutor

=== Version 0.3.0

=== Senior Project Group:

Joseph Walker, Chaskarandeep Singh,Deep Patel

== Rules:

1. Please do not complete your own pull requests if there is a large amount of commits.  Those pull requests should be reviewed by a second group member.

2. Commit and Push often.

== Git command line Senior Project:

=== Contributors - 

Joseph Walker, Chaskarandeep Singh, Deep Patel, Ori Maci, Sarthak Khatiwada

=== Instructions:

*Set up*

0.  If Deep or Mentu, fork this repository and clone your fork.

1.  Otherwise, Clone this repository. `git clone https://github.com/joey-walker/COMP650-SeniorProject.git`

2.  To start your development environment, enter the COMP650-SeniorProject directory. `cd Comp650-SeniorProject`

3.  `vagrant up`

4.  After vagrant initializes, do `vagrant ssh` to login.

5.  Optional - become (G)root `sudo -s`.  Otherwise you may need to have sudo before most commands.

*To install*

1. Enter the git directory we cloned in `cd git`

2. type `make install`

*To switch git versions in vagrant*

>Ask Prof. Joey (cause I'm lazy), probably some meddling with the PATH.

*Git instructions for fetching, merging, committing ,and pushing work*




== Git Gui Senior Project:

=== Contributors - 

Joseph Walker, Chaskarandeep Singh, Deep Patel

=== Instructions:

Coming soon.