= Senior project and Open Source Readme

== Git Tutor installation

=== Version 0.1.0

=== Instructions:


==Linux :
installation currently tested with ubuntu.

Install dependencies:

Ubuntu:

sudo apt-get install libcurl4-gnutls-dev libexpat1-dev gettext \ libz-dev libssl-dev

Debian: 

sudo yum install curl-devel expat-devel gettext-devel \ openssl-devel zlib-devel

1. clone https://github.com/joey-walker/git.git

2. cd into the git directory , and do `make install`

3. Switch git versions, to point to the new bin files located in the above directory from /git/.

==Windows:

1. Download https://msysgit.github.io/

2. Install to C:\Users\<your name>\gitbuild

3. Delete the git folder within gitbuild (gitbuild\git)

4. Either clone our git version into gitbuild, or move the pre-existing git folder into gitbuild (C:\Users\<your name>\git into C:\Users\<your name>\gitbuild )

5. Execute msys.bat from the gitbuild folder.

6. cd into gitbuild/git

7. type make and hit enter

8.  if you see common-cmds.h:19: error: 'N_' undeclared here (not in a function) or something similar. Edit commons-cmds.h and make sure that each N_ is on one line. The ending quotation being on the second line, will break the make.

9. Git tutor will be usable within ./git folder. If want to be used anywhere, switch out the git version.
